### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by necroen** [uoip/g2opy#14]
g2opy/python/core/eigen_types.h:185:82: 
error: no matches converting function ‘x’ to type ‘double (class Eigen::Quaternion<double>::*)() const’.def("x", (double (Eigen::Quaterniond::*) () const) &Eigen::Quaterniond::x)

ubuntu 16.04
anaconda3  python 3.6.4

i installed python version of pangolin correctly.

**Comment by necroen** [comment]
it is the eigen3 version problem, an older version eigen3 would work

**Comment by pineappleKID** [comment]
eigen-3.3.5 fail
eigen-3.3.4 pass

**Comment by zehongs** [comment]
Use `brew install eigen` only gives you the latest version.
[Try this](https://gist.github.com/ShenZehong/cbca774b8d28e84a3a987c80afe6df52), I cloned homebrew repo, and find eigen-3.3.4 commit.
