### ISSUE TITLE
Error while building g2o.cpp.obj

### ISSUE THREAD

**Issue by meh369** [uoip/g2opy#27]
![dsadsad](https://user-images.githubusercontent.com/37578727/52882726-a2535c80-318e-11e9-9a7f-509363b750c4.JPG)

**Comment by meh369** [comment]
Im using window 10

**Comment by meh369** [comment]
So I'm trying to compile the firmware, first I did Cmake g2o with suitesparse(Cholmod and its dependencies), Eigen3 and Qt5.4 and generated it to Visual Studio solution "g2o.sln" file(using VS-15 2017) that can build g2o. However, after building INSTALL(shown in the snip) I get 3 errors in timeutil.h file and when I located the file it had a typedef struct statement but I couldn't figure out the actual error. Help? 



![capture](https://user-images.githubusercontent.com/37578727/53759255-ddbb8e00-3ee5-11e9-9217-f6c68fca706e.JPG)



![capture2](https://user-images.githubusercontent.com/37578727/53759480-73efb400-3ee6-11e9-8166-a263c3fac1ff.JPG)

**Comment by vhgnguyen** [comment]
hi @meh369  i am having the same error as you while building with VS-15-2017 x64. Did you solve this?

**Comment by shrddr** [comment]
It has been fixed back in 2017, take a look here
https://github.com/RainerKuemmerle/g2o/blob/master/g2o/stuff/timeutil.h
https://github.com/RainerKuemmerle/g2o/blob/master/g2o/stuff/timeutil.cpp

**Comment by meh369** [comment]
> hi @meh369 i am having the same error as you while building with VS-15-2017 x64. Did you solve this?

No, I switched to Linux OS...
