### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by ankuku** [uoip/g2opy#36]
`fatal error: Python.h: No such file or directory
compilation terminated.
python/CMakeFiles/g2o.dir/build.make:62: recipe for target 'python/CMakeFiles/g2o.dir/g2o.cpp.o' failed
make[2]: *** [python/CMakeFiles/g2o.dir/g2o.cpp.o] Error 1
CMakeFiles/Makefile2:1577: recipe for target 'python/CMakeFiles/g2o.dir/all' failed
make[1]: *** [python/CMakeFiles/g2o.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

If this error occurs at some point, most likely you do not have installed `python3-dev`. Install using `sudo apt install python3-dev` and it should work.

**Comment by markfilan** [comment]
Python.h is used by GNU Compiler Collection (gcc) to build applications. You need to install a package called python-dev for building Python modules, extending the Python interpreter or embedding Python in applications.  You encounter "[Python.h](http://net-informations.com/python/err/pyh.htm): No such file or directory" error while trying to build a shared library using the file extension of another language ( e.g. 'C' ). If you are trying to build a shared library using the file extension of another language, you need to install the correct development version of Python.

Reason for this error:

- You haven't properly installed the header files and static libraries for python dev.
- Also, sometimes include files might not be default in the include path.

How to solve this error:

- Install the missing files and libraries.
- Include Path and Library.
- Finally, Compile it.
